// <auto-generated />
using System;
using EFP48.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFP48.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260315104717_NewDataSeed")]
    partial class NewDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFP48.Data.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("my_categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computers"
                        },
                        new
                        {
                            Id = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TV-sets"
                        },
                        new
                        {
                            Id = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mice"
                        },
                        new
                        {
                            Id = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keyboards"
                        },
                        new
                        {
                            Id = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cameras & Photography"
                        },
                        new
                        {
                            Id = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audio Equipment"
                        },
                        new
                        {
                            Id = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wearable Technology"
                        });
                });

            modelBuilder.Entity("EFP48.Data.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111111"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPhone 15",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111112"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S24",
                            Price = 899.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111113"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Google Pixel 8",
                            Price = 799.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111114"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi 14",
                            Price = 699.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111115"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OnePlus 12",
                            Price = 749.99000000000001
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222221"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell OptiPlex 7010",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222222"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP Pavilion Desktop",
                            Price = 950.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222223"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenovo ThinkCentre",
                            Price = 1100.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222224"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iMac 24",
                            Price = 1800.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222225"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ExpertCenter",
                            Price = 1050.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333331"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MacBook Air M3",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333332"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell XPS 15",
                            Price = 1700.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333333"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP Spectre x360",
                            Price = 1600.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333334"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenovo Legion 5",
                            Price = 1400.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333335"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ROG Zephyrus",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444441"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung QLED 55",
                            Price = 1300.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444442"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG OLED C3",
                            Price = 2100.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444443"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Bravia XR",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444444"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Philips Ambilight 65",
                            Price = 1700.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444445"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TCL 4K UHD",
                            Price = 900.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555551"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell UltraSharp 27",
                            Price = 600.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555552"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG UltraGear 32",
                            Price = 750.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555553"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Odyssey G7",
                            Price = 800.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555554"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ProArt Display",
                            Price = 950.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555555"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acer Predator XB",
                            Price = 850.0
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666661"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech MX Master 3",
                            Price = 120.0
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666662"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer DeathAdder V3",
                            Price = 99.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666663"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SteelSeries Rival 5",
                            Price = 79.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666664"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HyperX Pulsefire",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666665"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corsair Dark Core",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777771"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech MX Keys",
                            Price = 130.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777772"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer BlackWidow V4",
                            Price = 180.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777773"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corsair K95 RGB",
                            Price = 200.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777774"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SteelSeries Apex Pro",
                            Price = 210.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777775"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keychron K8",
                            Price = 110.0
                        },
                        new
                        {
                            Id = new Guid("d31f4cad-418c-4792-89f6-7a5f3cd65afb"),
                            CategoryId = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canon EOS R50",
                            Price = 829.0
                        },
                        new
                        {
                            Id = new Guid("d5276fcc-bf5e-4bec-9d61-e67f2906db69"),
                            CategoryId = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Alpha a6400",
                            Price = 898.0
                        },
                        new
                        {
                            Id = new Guid("f6c85122-e889-46d8-ac43-63dc0e8a01b2"),
                            CategoryId = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikon Z30",
                            Price = 706.0
                        },
                        new
                        {
                            Id = new Guid("aacc2981-b45b-457b-9b7a-22dff703400f"),
                            CategoryId = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GoPro HERO12 Black",
                            Price = 399.0
                        },
                        new
                        {
                            Id = new Guid("aacd266f-bf5c-4ac0-93ba-739c937f8c22"),
                            CategoryId = new Guid("89b21758-c1c1-469d-86f9-a3a8705f593c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fujifilm Instax Mini 12",
                            Price = 79.0
                        },
                        new
                        {
                            Id = new Guid("1279005e-64d9-4509-bbc0-59a979b55f82"),
                            CategoryId = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 349.0
                        },
                        new
                        {
                            Id = new Guid("443414ba-f852-4733-92e6-ded212c77fe7"),
                            CategoryId = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JBL Charge 5 Speaker",
                            Price = 179.0
                        },
                        new
                        {
                            Id = new Guid("eccc2c13-0b0f-43a1-ab12-3730b5183943"),
                            CategoryId = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bose Smart Soundbar 600",
                            Price = 499.0
                        },
                        new
                        {
                            Id = new Guid("b48fa24b-6876-4404-bd21-6e99cf5550ec"),
                            CategoryId = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blue Yeti USB Microphone",
                            Price = 129.0
                        },
                        new
                        {
                            Id = new Guid("bffdfb7d-73c9-4ab8-b9eb-34a63065427c"),
                            CategoryId = new Guid("020c4989-67a4-4e4b-afbc-1d39a0e5d00b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple AirPods Pro(2nd Gen)",
                            Price = 249.0
                        },
                        new
                        {
                            Id = new Guid("cd5c791f-c0cc-467f-bd96-40624a302f7d"),
                            CategoryId = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple Watch Series 9",
                            Price = 399.0
                        },
                        new
                        {
                            Id = new Guid("923df676-5088-4289-8ddc-050cd7ebfcd0"),
                            CategoryId = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy Watch 6",
                            Price = 299.0
                        },
                        new
                        {
                            Id = new Guid("a92c46dc-2037-44ae-9cc5-0ba08e07b401"),
                            CategoryId = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fitbit Charge 6",
                            Price = 159.0
                        },
                        new
                        {
                            Id = new Guid("41644484-cebf-4f2c-b9b4-f42d4d7f5076"),
                            CategoryId = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garmin Venu Sq",
                            Price = 249.0
                        },
                        new
                        {
                            Id = new Guid("217a73c9-4f13-455b-8daa-91bb194beb5a"),
                            CategoryId = new Guid("20f8768c-ab73-4cc6-8ebb-cc58fe00ad4d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oura Ring Gen3",
                            Price = 299.0
                        });
                });

            modelBuilder.Entity("EFP48.Data.Entity.Product", b =>
                {
                    b.HasOne("EFP48.Data.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFP48.Data.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
